[project]
name = "hands-on-machine-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ['numpy', 'pandas', 'scikit-learn', 'matplotlib']
